/* Created by Conner Recoskie,
   April 3rd,
   This program takes strings from the user to then change/calculate them in 
   a certain way using pre-defined methods.
*/

public class FrmStringMethods extends javax.swing.JFrame {
    // Creating varibles that will hold the users inputs, for the diffrent tasks. 
    String length1;
    String allCaps;
    String fourthSpot;
    String identical1;
    String identical2;
    String stringFound;
    String letterFound;
    String charFourToSix;
    String replaceA;
  
    public FrmStringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        lblInstructions2 = new javax.swing.JLabel();
        txtLowerCase = new javax.swing.JTextField();
        lblInstructions3 = new javax.swing.JLabel();
        txtCharAtFourth = new javax.swing.JTextField();
        lblInstructions4 = new javax.swing.JLabel();
        txtIdentical1 = new javax.swing.JTextField();
        txtIdentical2 = new javax.swing.JTextField();
        lblInstructions5 = new javax.swing.JLabel();
        txtString = new javax.swing.JTextField();
        txtLetter = new javax.swing.JTextField();
        lblInstructions6 = new javax.swing.JLabel();
        txtCharsFourToSix = new javax.swing.JTextField();
        lblInstructions7 = new javax.swing.JLabel();
        txtReplaceA = new javax.swing.JTextField();
        btnCaps = new javax.swing.JButton();
        btnLength = new javax.swing.JButton();
        btnFourthSpot = new javax.swing.JButton();
        btnIdentical = new javax.swing.JButton();
        btnLetterFound = new javax.swing.JButton();
        btnCharacter = new javax.swing.JButton();
        btnReplacesA = new javax.swing.JButton();
        lblLengthAnswer = new javax.swing.JLabel();
        lblAllCapsAnswer = new javax.swing.JLabel();
        lblFourthSpot = new javax.swing.JLabel();
        lblIdenticalAnswer = new javax.swing.JLabel();
        lblLetterFoundAnswer = new javax.swing.JLabel();
        lblCharFourToSix = new javax.swing.JLabel();
        lblReplacesA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 255));
        lblTitle.setText("Super String Software");

        lblInstructions1.setText("Enter a String. The program will output the number of characters that are in the Sting:");

        lblInstructions2.setText("Enter a String using lower case numbers. The program will output the String in all capital letters:");

        lblInstructions3.setText("Enter a String. The program will output the character at the 4th spot: ");

        lblInstructions4.setText("Enter two Strings. The program will output whether or not they are identical:");

        lblInstructions5.setText("Enter a String and a letter. The program will output whether or not the letter is found in the String: ");

        lblInstructions6.setText("Enter a string that is atleast 8 characters long. The program will output characters 4 to 6: ");

        lblInstructions7.setText("Enter a String that contains at least one \"a\". The program will then replace all occurences of \"a\" with \"x\": ");

        btnCaps.setText("All Caps");
        btnCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapsActionPerformed(evt);
            }
        });

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        btnFourthSpot.setText("4th Spot");
        btnFourthSpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourthSpotActionPerformed(evt);
            }
        });

        btnIdentical.setText("Identical?");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        btnLetterFound.setText("Letter Found?");
        btnLetterFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetterFoundActionPerformed(evt);
            }
        });

        btnCharacter.setText("Characters 4 to 6");
        btnCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharacterActionPerformed(evt);
            }
        });

        btnReplacesA.setText("Replaces \"a\"");
        btnReplacesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplacesAActionPerformed(evt);
            }
        });

        lblLengthAnswer.setText("-");

        lblAllCapsAnswer.setText("-");

        lblFourthSpot.setText("-");

        lblIdenticalAnswer.setText("-");

        lblLetterFoundAnswer.setText("-");

        lblCharFourToSix.setText("-");

        lblReplacesA.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtReplaceA, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(btnReplacesA)
                        .addGap(55, 55, 55)
                        .addComponent(lblReplacesA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInstructions1)
                    .addComponent(lblInstructions3)
                    .addComponent(lblInstructions2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblInstructions4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCharAtFourth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLowerCase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCaps, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnFourthSpot, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(59, 59, 59))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnIdentical)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblInstructions7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAllCapsAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFourthSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdenticalAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(txtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(btnLetterFound)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLetterFoundAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCharsFourToSix, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(172, 172, 172)
                                    .addComponent(btnCharacter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCharFourToSix, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(lblInstructions6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblInstructions5))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(btnLength)
                .addGap(53, 53, 53)
                .addComponent(lblLengthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblInstructions1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLength)
                    .addComponent(lblLengthAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllCapsAnswer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLowerCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCaps)))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharAtFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFourthSpot)
                    .addComponent(lblFourthSpot))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdentical)
                    .addComponent(lblIdenticalAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLetterFound)
                    .addComponent(lblLetterFoundAnswer))
                .addGap(18, 18, 18)
                .addComponent(lblInstructions6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharsFourToSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacter)
                    .addComponent(lblCharFourToSix))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblInstructions7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReplaceA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplacesA)
                    .addComponent(lblReplacesA))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        // Getting the users input for a word they want the length of.
        length1 = txtLength.getText();
        
        //Calculating and displaying the length of the string to the GUI.
        lblLengthAnswer.setText(String.valueOf(length1.length()));
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapsActionPerformed
        // Getting the users input for a string they want to get in all caps.
        allCaps = txtLowerCase.getText();
        
         //Calculating and displaying the string in all caps to the GUI.
        lblAllCapsAnswer.setText(String.valueOf(allCaps.toUpperCase()));
    }//GEN-LAST:event_btnCapsActionPerformed

    private void btnFourthSpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourthSpotActionPerformed
       // Getting the users input of a string.
       fourthSpot = txtCharAtFourth.getText();
       
       /* Calculating for the character at the index of 3 and outputting it to 
       the GUI. */
       lblFourthSpot.setText(String.valueOf(fourthSpot.charAt(3)));
    }//GEN-LAST:event_btnFourthSpotActionPerformed

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
        // Getting two strings from user.
        identical1 = txtIdentical1.getText();
        identical2 = txtIdentical2.getText();
        
        /* Checking if the strings are identical. If they are,
        true will be outputted to the GUI. If not, false will be out-putted 
        to the GUI. */
        lblIdenticalAnswer.setText(String.valueOf(identical1.equals(identical2)));
    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnLetterFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetterFoundActionPerformed
       // Getting a word and a letter from the user.
        stringFound = txtString.getText();
       letterFound = txtLetter.getText();
       
       /* Checking if the letter inputted is in the word. If it is,
        true will be outputted to the GUI. If not, false will be out-putted 
        to the GUI.  */
       lblLetterFoundAnswer.setText(String.valueOf(stringFound.contains
        (letterFound)));
    }//GEN-LAST:event_btnLetterFoundActionPerformed

    private void btnCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharacterActionPerformed
        // Getting a string that is 8+ characters long from user.
        charFourToSix = txtCharsFourToSix.getText();
        
        // Calculating and displying the letters at the index's of 3,4,5.
        lblCharFourToSix.setText(String.valueOf(charFourToSix.charAt(3)) +
                String.valueOf(charFourToSix.charAt(4)) + 
                String.valueOf(charFourToSix.charAt(5)));
    }//GEN-LAST:event_btnCharacterActionPerformed

    private void btnReplacesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplacesAActionPerformed
        // Getting a string from the user
        replaceA = txtReplaceA.getText();
        
        /* Replacing any a's in the string with x's and outputting the word 
       to the GUI.*/
        lblReplacesA.setText(String.valueOf(replaceA.replace("a", "x")));
    }//GEN-LAST:event_btnReplacesAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaps;
    private javax.swing.JButton btnCharacter;
    private javax.swing.JButton btnFourthSpot;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLetterFound;
    private javax.swing.JButton btnReplacesA;
    private javax.swing.JLabel lblAllCapsAnswer;
    private javax.swing.JLabel lblCharFourToSix;
    private javax.swing.JLabel lblFourthSpot;
    private javax.swing.JLabel lblIdenticalAnswer;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblInstructions4;
    private javax.swing.JLabel lblInstructions5;
    private javax.swing.JLabel lblInstructions6;
    private javax.swing.JLabel lblInstructions7;
    private javax.swing.JLabel lblLengthAnswer;
    private javax.swing.JLabel lblLetterFoundAnswer;
    private javax.swing.JLabel lblReplacesA;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCharAtFourth;
    private javax.swing.JTextField txtCharsFourToSix;
    private javax.swing.JTextField txtIdentical1;
    private javax.swing.JTextField txtIdentical2;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtLetter;
    private javax.swing.JTextField txtLowerCase;
    private javax.swing.JTextField txtReplaceA;
    private javax.swing.JTextField txtString;
    // End of variables declaration//GEN-END:variables
}
